schema_version = "1.0.0"

id = "continuum_flow"
version = "0.2.0"
name = "Continuum Flow"
tagline = "Smoke and fire simulator"
maintainer = "Lutz Rohlfing"
type = "add-on"

website = "https://lutzr2000.github.io/Continuum_Flow/"
tags = ["Physics"]

blender_version_min = "5.1.0"

platforms = ["windows-x64"]

license = [
    "SPDX:GPL-3.0-or-later",
]

wheels = [
    "./wheels/numpy-2.4.6-cp313-cp313-win_amd64.whl",
    "./wheels/trimesh-4.12.2-py3-none-any.whl",
    "./wheels/pyopencl-2026.1.4-cp313-cp313-win_amd64.whl",
    "./wheels/pytools-2026.1.1-py3-none-any.whl",
    "./wheels/siphash24-1.9-cp313-cp313-win_amd64.whl"
]

[permissions]
files = "Read and write simulation cache files"
